<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openweathermapstore.proto

namespace Openweathermapstore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>openweathermapstore.Current</code>
 */
class Current extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Dt = 1 [json_name = "dt"];</code>
     */
    protected $Dt = 0;
    /**
     * Generated from protobuf field <code>int32 Sunrise = 2 [json_name = "sunrise"];</code>
     */
    protected $Sunrise = 0;
    /**
     * Generated from protobuf field <code>int32 Sunset = 3 [json_name = "sunset"];</code>
     */
    protected $Sunset = 0;
    /**
     * Generated from protobuf field <code>float Temp = 4 [json_name = "temp"];</code>
     */
    protected $Temp = 0.0;
    /**
     * Generated from protobuf field <code>float FeelsLike = 5 [json_name = "feels_like"];</code>
     */
    protected $FeelsLike = 0.0;
    /**
     * Generated from protobuf field <code>int32 Pressure = 6 [json_name = "pressure"];</code>
     */
    protected $Pressure = 0;
    /**
     * Generated from protobuf field <code>int32 Humidity = 7 [json_name = "humidity"];</code>
     */
    protected $Humidity = 0;
    /**
     * Generated from protobuf field <code>float DewPoint = 8 [json_name = "dew_point"];</code>
     */
    protected $DewPoint = 0.0;
    /**
     * Generated from protobuf field <code>float Uvi = 9 [json_name = "uvi"];</code>
     */
    protected $Uvi = 0.0;
    /**
     * Generated from protobuf field <code>int32 Clouds = 10 [json_name = "clouds"];</code>
     */
    protected $Clouds = 0;
    /**
     * Generated from protobuf field <code>int32 Visibility = 11 [json_name = "visibility"];</code>
     */
    protected $Visibility = 0;
    /**
     * Generated from protobuf field <code>float WindSpeed = 12 [json_name = "wind_speed"];</code>
     */
    protected $WindSpeed = 0.0;
    /**
     * Generated from protobuf field <code>int32 WindDeg = 13 [json_name = "wind_deg"];</code>
     */
    protected $WindDeg = 0;
    /**
     * Generated from protobuf field <code>float WindGust = 14 [json_name = "wind_gust"];</code>
     */
    protected $WindGust = 0.0;
    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Weather Weather = 15 [json_name = "weather"];</code>
     */
    private $Weather;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Dt
     *     @type int $Sunrise
     *     @type int $Sunset
     *     @type float $Temp
     *     @type float $FeelsLike
     *     @type int $Pressure
     *     @type int $Humidity
     *     @type float $DewPoint
     *     @type float $Uvi
     *     @type int $Clouds
     *     @type int $Visibility
     *     @type float $WindSpeed
     *     @type int $WindDeg
     *     @type float $WindGust
     *     @type \Openweathermapstore\Weather[] $Weather
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Openweathermapstore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 Dt = 1 [json_name = "dt"];</code>
     * @return int
     */
    public function getDt()
    {
        return $this->Dt;
    }

    /**
     * Generated from protobuf field <code>int32 Dt = 1 [json_name = "dt"];</code>
     * @param int $var
     * @return $this
     */
    public function setDt(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->Dt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Sunrise = 2 [json_name = "sunrise"];</code>
     * @return int
     */
    public function getSunrise()
    {
        return $this->Sunrise;
    }

    /**
     * Generated from protobuf field <code>int32 Sunrise = 2 [json_name = "sunrise"];</code>
     * @param int $var
     * @return $this
     */
    public function setSunrise(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->Sunrise = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Sunset = 3 [json_name = "sunset"];</code>
     * @return int
     */
    public function getSunset()
    {
        return $this->Sunset;
    }

    /**
     * Generated from protobuf field <code>int32 Sunset = 3 [json_name = "sunset"];</code>
     * @param int $var
     * @return $this
     */
    public function setSunset(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->Sunset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Temp = 4 [json_name = "temp"];</code>
     * @return float
     */
    public function getTemp()
    {
        return $this->Temp;
    }

    /**
     * Generated from protobuf field <code>float Temp = 4 [json_name = "temp"];</code>
     * @param float $var
     * @return $this
     */
    public function setTemp(float $var)
    {
        $this->Temp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float FeelsLike = 5 [json_name = "feels_like"];</code>
     * @return float
     */
    public function getFeelsLike()
    {
        return $this->FeelsLike;
    }

    /**
     * Generated from protobuf field <code>float FeelsLike = 5 [json_name = "feels_like"];</code>
     * @param float $var
     * @return $this
     */
    public function setFeelsLike(float $var)
    {
        $this->FeelsLike = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Pressure = 6 [json_name = "pressure"];</code>
     * @return int
     */
    public function getPressure()
    {
        return $this->Pressure;
    }

    /**
     * Generated from protobuf field <code>int32 Pressure = 6 [json_name = "pressure"];</code>
     * @param int $var
     * @return $this
     */
    public function setPressure(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->Pressure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Humidity = 7 [json_name = "humidity"];</code>
     * @return int
     */
    public function getHumidity()
    {
        return $this->Humidity;
    }

    /**
     * Generated from protobuf field <code>int32 Humidity = 7 [json_name = "humidity"];</code>
     * @param int $var
     * @return $this
     */
    public function setHumidity(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->Humidity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float DewPoint = 8 [json_name = "dew_point"];</code>
     * @return float
     */
    public function getDewPoint()
    {
        return $this->DewPoint;
    }

    /**
     * Generated from protobuf field <code>float DewPoint = 8 [json_name = "dew_point"];</code>
     * @param float $var
     * @return $this
     */
    public function setDewPoint(float $var)
    {
        $this->DewPoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Uvi = 9 [json_name = "uvi"];</code>
     * @return float
     */
    public function getUvi()
    {
        return $this->Uvi;
    }

    /**
     * Generated from protobuf field <code>float Uvi = 9 [json_name = "uvi"];</code>
     * @param float $var
     * @return $this
     */
    public function setUvi(float $var)
    {
        $this->Uvi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Clouds = 10 [json_name = "clouds"];</code>
     * @return int
     */
    public function getClouds()
    {
        return $this->Clouds;
    }

    /**
     * Generated from protobuf field <code>int32 Clouds = 10 [json_name = "clouds"];</code>
     * @param int $var
     * @return $this
     */
    public function setClouds(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->Clouds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Visibility = 11 [json_name = "visibility"];</code>
     * @return int
     */
    public function getVisibility()
    {
        return $this->Visibility;
    }

    /**
     * Generated from protobuf field <code>int32 Visibility = 11 [json_name = "visibility"];</code>
     * @param int $var
     * @return $this
     */
    public function setVisibility(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->Visibility = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float WindSpeed = 12 [json_name = "wind_speed"];</code>
     * @return float
     */
    public function getWindSpeed()
    {
        return $this->WindSpeed;
    }

    /**
     * Generated from protobuf field <code>float WindSpeed = 12 [json_name = "wind_speed"];</code>
     * @param float $var
     * @return $this
     */
    public function setWindSpeed(float $var)
    {
        $this->WindSpeed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 WindDeg = 13 [json_name = "wind_deg"];</code>
     * @return int
     */
    public function getWindDeg()
    {
        return $this->WindDeg;
    }

    /**
     * Generated from protobuf field <code>int32 WindDeg = 13 [json_name = "wind_deg"];</code>
     * @param int $var
     * @return $this
     */
    public function setWindDeg(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->WindDeg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float WindGust = 14 [json_name = "wind_gust"];</code>
     * @return float
     */
    public function getWindGust()
    {
        return $this->WindGust;
    }

    /**
     * Generated from protobuf field <code>float WindGust = 14 [json_name = "wind_gust"];</code>
     * @param float $var
     * @return $this
     */
    public function setWindGust(float $var)
    {
        $this->WindGust = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Weather Weather = 15 [json_name = "weather"];</code>
     * @return RepeatedField<\Openweathermapstore\Weather>
     */
    public function getWeather()
    {
        return $this->Weather;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Weather Weather = 15 [json_name = "weather"];</code>
     * @param \Openweathermapstore\Weather[] $var
     * @return $this
     */
    public function setWeather(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openweathermapstore\Weather::class);
        $this->Weather = $arr;

        return $this;
    }

}

