<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openweathermapstore.proto

namespace Openweathermapstore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>openweathermapstore.GetWeatherDataResponse</code>
 */
class GetWeatherDataResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 LastUpdated = 1;</code>
     */
    protected $LastUpdated = 0;
    /**
     * Generated from protobuf field <code>float Lat = 2 [json_name = "lat"];</code>
     */
    protected $Lat = 0.0;
    /**
     * Generated from protobuf field <code>float Lon = 3 [json_name = "lon"];</code>
     */
    protected $Lon = 0.0;
    /**
     * Generated from protobuf field <code>string Timezone = 4 [json_name = "timezone"];</code>
     */
    protected $Timezone = '';
    /**
     * Generated from protobuf field <code>int32 TimezoneOffset = 5 [json_name = "timezone_offset"];</code>
     */
    protected $TimezoneOffset = 0;
    /**
     * Generated from protobuf field <code>.openweathermapstore.Current Current = 6 [json_name = "current"];</code>
     */
    protected $Current = null;
    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Minutely Minutely = 7 [json_name = "minutely"];</code>
     */
    private $Minutely;
    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Hourly Hourly = 8 [json_name = "hourly"];</code>
     */
    private $Hourly;
    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Daily Daily = 9 [json_name = "daily"];</code>
     */
    private $Daily;
    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Alert Alerts = 10 [json_name = "alerts"];</code>
     */
    private $Alerts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $LastUpdated
     *     @type float $Lat
     *     @type float $Lon
     *     @type string $Timezone
     *     @type int $TimezoneOffset
     *     @type \Openweathermapstore\Current $Current
     *     @type \Openweathermapstore\Minutely[] $Minutely
     *     @type \Openweathermapstore\Hourly[] $Hourly
     *     @type \Openweathermapstore\Daily[] $Daily
     *     @type \Openweathermapstore\Alert[] $Alerts
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Openweathermapstore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 LastUpdated = 1;</code>
     * @return int|string
     */
    public function getLastUpdated()
    {
        return $this->LastUpdated;
    }

    /**
     * Generated from protobuf field <code>int64 LastUpdated = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastUpdated(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->LastUpdated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Lat = 2 [json_name = "lat"];</code>
     * @return float
     */
    public function getLat()
    {
        return $this->Lat;
    }

    /**
     * Generated from protobuf field <code>float Lat = 2 [json_name = "lat"];</code>
     * @param float $var
     * @return $this
     */
    public function setLat(float $var)
    {
        $this->Lat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Lon = 3 [json_name = "lon"];</code>
     * @return float
     */
    public function getLon()
    {
        return $this->Lon;
    }

    /**
     * Generated from protobuf field <code>float Lon = 3 [json_name = "lon"];</code>
     * @param float $var
     * @return $this
     */
    public function setLon(float $var)
    {
        $this->Lon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Timezone = 4 [json_name = "timezone"];</code>
     * @return string
     */
    public function getTimezone()
    {
        return $this->Timezone;
    }

    /**
     * Generated from protobuf field <code>string Timezone = 4 [json_name = "timezone"];</code>
     * @param string $var
     * @return $this
     */
    public function setTimezone(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->Timezone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 TimezoneOffset = 5 [json_name = "timezone_offset"];</code>
     * @return int
     */
    public function getTimezoneOffset()
    {
        return $this->TimezoneOffset;
    }

    /**
     * Generated from protobuf field <code>int32 TimezoneOffset = 5 [json_name = "timezone_offset"];</code>
     * @param int $var
     * @return $this
     */
    public function setTimezoneOffset(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->TimezoneOffset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openweathermapstore.Current Current = 6 [json_name = "current"];</code>
     * @return \Openweathermapstore\Current|null
     */
    public function getCurrent()
    {
        return $this->Current;
    }

    public function hasCurrent()
    {
        return isset($this->Current);
    }

    public function clearCurrent()
    {
        unset($this->Current);
    }

    /**
     * Generated from protobuf field <code>.openweathermapstore.Current Current = 6 [json_name = "current"];</code>
     * @param \Openweathermapstore\Current $var
     * @return $this
     */
    public function setCurrent(\Openweathermapstore\Current|null $var)
    {
        $this->Current = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Minutely Minutely = 7 [json_name = "minutely"];</code>
     * @return RepeatedField<\Openweathermapstore\Minutely>
     */
    public function getMinutely()
    {
        return $this->Minutely;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Minutely Minutely = 7 [json_name = "minutely"];</code>
     * @param \Openweathermapstore\Minutely[] $var
     * @return $this
     */
    public function setMinutely(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openweathermapstore\Minutely::class);
        $this->Minutely = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Hourly Hourly = 8 [json_name = "hourly"];</code>
     * @return RepeatedField<\Openweathermapstore\Hourly>
     */
    public function getHourly()
    {
        return $this->Hourly;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Hourly Hourly = 8 [json_name = "hourly"];</code>
     * @param \Openweathermapstore\Hourly[] $var
     * @return $this
     */
    public function setHourly(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openweathermapstore\Hourly::class);
        $this->Hourly = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Daily Daily = 9 [json_name = "daily"];</code>
     * @return RepeatedField<\Openweathermapstore\Daily>
     */
    public function getDaily()
    {
        return $this->Daily;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Daily Daily = 9 [json_name = "daily"];</code>
     * @param \Openweathermapstore\Daily[] $var
     * @return $this
     */
    public function setDaily(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openweathermapstore\Daily::class);
        $this->Daily = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Alert Alerts = 10 [json_name = "alerts"];</code>
     * @return RepeatedField<\Openweathermapstore\Alert>
     */
    public function getAlerts()
    {
        return $this->Alerts;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Alert Alerts = 10 [json_name = "alerts"];</code>
     * @param \Openweathermapstore\Alert[] $var
     * @return $this
     */
    public function setAlerts(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openweathermapstore\Alert::class);
        $this->Alerts = $arr;

        return $this;
    }

}

