<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openweathermapstore.proto

namespace Openweathermapstore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>openweathermapstore.Weather</code>
 */
class Weather extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 ID = 1 [json_name = "id"];</code>
     */
    protected $ID = 0;
    /**
     * Generated from protobuf field <code>string Main = 2 [json_name = "main"];</code>
     */
    protected $Main = '';
    /**
     * Generated from protobuf field <code>string Description = 3 [json_name = "description"];</code>
     */
    protected $Description = '';
    /**
     * Generated from protobuf field <code>string Icon = 4 [json_name = "icon"];</code>
     */
    protected $Icon = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ID
     *     @type string $Main
     *     @type string $Description
     *     @type string $Icon
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Openweathermapstore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 ID = 1 [json_name = "id"];</code>
     * @return int
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * Generated from protobuf field <code>int32 ID = 1 [json_name = "id"];</code>
     * @param int $var
     * @return $this
     */
    public function setID(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->ID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Main = 2 [json_name = "main"];</code>
     * @return string
     */
    public function getMain()
    {
        return $this->Main;
    }

    /**
     * Generated from protobuf field <code>string Main = 2 [json_name = "main"];</code>
     * @param string $var
     * @return $this
     */
    public function setMain(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->Main = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Description = 3 [json_name = "description"];</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->Description;
    }

    /**
     * Generated from protobuf field <code>string Description = 3 [json_name = "description"];</code>
     * @param string $var
     * @return $this
     */
    public function setDescription(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->Description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Icon = 4 [json_name = "icon"];</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->Icon;
    }

    /**
     * Generated from protobuf field <code>string Icon = 4 [json_name = "icon"];</code>
     * @param string $var
     * @return $this
     */
    public function setIcon(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->Icon = $var;

        return $this;
    }

}

