<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openweathermapstore.proto

namespace GPBMetadata;

class Openweathermapstore
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ú
openweathermapstore.protoopenweathermapstore"
GetWeatherDataRequest"c
Weather
ID (Rid
Main (	Rmain 
Description (	Rdescription
Icon (	Ricon"¬
Current
Dt (Rdt
Sunrise (Rsunrise
Sunset (Rsunset
Temp (Rtemp
	FeelsLike (R
feels_like
Pressure (Rpressure
Humidity (Rhumidity
DewPoint (R	dew_point
Uvi	 (Ruvi
Clouds
 (Rclouds

Visibility (R
visibility
	WindSpeed (R
wind_speed
WindDeg (Rwind_deg
WindGust (R	wind_gust6
Weather (2.openweathermapstore.WeatherRweather"@
Minutely
Dt (Rdt$
Precipitation (Rprecipitation"‹
Hourly
Dt (Rdt
Temp (Rtemp
	FeelsLike (R
feels_like
Pressure (Rpressure
Humidity (Rhumidity
DewPoint (R	dew_point
Uvi (Ruvi
Clouds (Rclouds

Visibility	 (R
visibility
	WindSpeed
 (R
wind_speed
WindDeg (Rwind_deg
WindGust (R	wind_gust6
Weather (2.openweathermapstore.WeatherRweather
Pop (Rpop"À
Daily
Dt (Rdt
Sunrise (Rsunrise
Sunset (Rsunset
Moonrise (Rmoonrise
Moonset (Rmoonset
	MoonPhase (R
moon_phase-
Temp (2.openweathermapstore.TempRtemp=
	FeelsLike (2.openweathermapstore.FeelsLikeR
feels_like
Pressure	 (Rpressure
Humidity
 (Rhumidity
DewPoint (R	dew_point
	WindSpeed (R
wind_speed
WindDeg (Rwind_deg
WindGust (R	wind_gust6
Weather (2.openweathermapstore.WeatherRweather
Clouds (Rclouds
Pop (Rpop
Rain (Rrain
Uvi (Ruvi"x
Temp
Day (Rday
Min (Rmin
Max (Rmax
Night (Rnight
Eve (Reve
Morn (Rmorn"Y
	FeelsLike
Day (Rday
Night (Rnight
Eve (Reve
Morn (Rmorn"œ
Alert

SenderName (	Rsender_name
Event (	Revent
Start (Rstart
End (Rend 
Description (	Rdescription
Tags (	Rtags"¤
GetWeatherDataResponse
LastUpdated (
Lat (Rlat
Lon (Rlon
Timezone (	Rtimezone\'
TimezoneOffset (Rtimezone_offset6
Current (2.openweathermapstore.CurrentRcurrent9
Minutely (2.openweathermapstore.MinutelyRminutely3
Hourly (2.openweathermapstore.HourlyRhourly0
Daily	 (2.openweathermapstore.DailyRdaily2
Alerts
 (2.openweathermapstore.AlertRalerts2†
OpenWeatherMapStoreServeri
GetWeatherData*.openweathermapstore.GetWeatherDataRequest+.openweathermapstore.GetWeatherDataResponseB<Z:giedrius-slegeris/openweathermap-store;openweathermapstorebproto3'
        , true);

        static::$is_initialized = true;
    }
}

