<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openweathermapstore.proto

namespace Openweathermapstore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openweathermapstore.Alert</code>
 */
class Alert extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string SenderName = 1 [json_name = "sender_name"];</code>
     */
    protected $SenderName = '';
    /**
     * Generated from protobuf field <code>string Event = 2 [json_name = "event"];</code>
     */
    protected $Event = '';
    /**
     * Generated from protobuf field <code>int64 Start = 3 [json_name = "start"];</code>
     */
    protected $Start = 0;
    /**
     * Generated from protobuf field <code>int64 End = 4 [json_name = "end"];</code>
     */
    protected $End = 0;
    /**
     * Generated from protobuf field <code>string Description = 5 [json_name = "description"];</code>
     */
    protected $Description = '';
    /**
     * Generated from protobuf field <code>repeated string Tags = 6 [json_name = "tags"];</code>
     */
    private $Tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $SenderName
     *     @type string $Event
     *     @type int|string $Start
     *     @type int|string $End
     *     @type string $Description
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $Tags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openweathermapstore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string SenderName = 1 [json_name = "sender_name"];</code>
     * @return string
     */
    public function getSenderName()
    {
        return $this->SenderName;
    }

    /**
     * Generated from protobuf field <code>string SenderName = 1 [json_name = "sender_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setSenderName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SenderName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Event = 2 [json_name = "event"];</code>
     * @return string
     */
    public function getEvent()
    {
        return $this->Event;
    }

    /**
     * Generated from protobuf field <code>string Event = 2 [json_name = "event"];</code>
     * @param string $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkString($var, True);
        $this->Event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Start = 3 [json_name = "start"];</code>
     * @return int|string
     */
    public function getStart()
    {
        return $this->Start;
    }

    /**
     * Generated from protobuf field <code>int64 Start = 3 [json_name = "start"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkInt64($var);
        $this->Start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 End = 4 [json_name = "end"];</code>
     * @return int|string
     */
    public function getEnd()
    {
        return $this->End;
    }

    /**
     * Generated from protobuf field <code>int64 End = 4 [json_name = "end"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setEnd($var)
    {
        GPBUtil::checkInt64($var);
        $this->End = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Description = 5 [json_name = "description"];</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->Description;
    }

    /**
     * Generated from protobuf field <code>string Description = 5 [json_name = "description"];</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->Description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string Tags = 6 [json_name = "tags"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->Tags;
    }

    /**
     * Generated from protobuf field <code>repeated string Tags = 6 [json_name = "tags"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Tags = $arr;

        return $this;
    }

}

