<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openweathermap-store.proto

namespace Openweathermap_store;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openweathermap_store.FeelsLike</code>
 */
class FeelsLike extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float Day = 1 [json_name = "day"];</code>
     */
    protected $Day = 0.0;
    /**
     * Generated from protobuf field <code>float Night = 2 [json_name = "night"];</code>
     */
    protected $Night = 0.0;
    /**
     * Generated from protobuf field <code>float Eve = 3 [json_name = "eve"];</code>
     */
    protected $Eve = 0.0;
    /**
     * Generated from protobuf field <code>float Morn = 4 [json_name = "morn"];</code>
     */
    protected $Morn = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $Day
     *     @type float $Night
     *     @type float $Eve
     *     @type float $Morn
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OpenweathermapStore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float Day = 1 [json_name = "day"];</code>
     * @return float
     */
    public function getDay()
    {
        return $this->Day;
    }

    /**
     * Generated from protobuf field <code>float Day = 1 [json_name = "day"];</code>
     * @param float $var
     * @return $this
     */
    public function setDay($var)
    {
        GPBUtil::checkFloat($var);
        $this->Day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Night = 2 [json_name = "night"];</code>
     * @return float
     */
    public function getNight()
    {
        return $this->Night;
    }

    /**
     * Generated from protobuf field <code>float Night = 2 [json_name = "night"];</code>
     * @param float $var
     * @return $this
     */
    public function setNight($var)
    {
        GPBUtil::checkFloat($var);
        $this->Night = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Eve = 3 [json_name = "eve"];</code>
     * @return float
     */
    public function getEve()
    {
        return $this->Eve;
    }

    /**
     * Generated from protobuf field <code>float Eve = 3 [json_name = "eve"];</code>
     * @param float $var
     * @return $this
     */
    public function setEve($var)
    {
        GPBUtil::checkFloat($var);
        $this->Eve = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Morn = 4 [json_name = "morn"];</code>
     * @return float
     */
    public function getMorn()
    {
        return $this->Morn;
    }

    /**
     * Generated from protobuf field <code>float Morn = 4 [json_name = "morn"];</code>
     * @param float $var
     * @return $this
     */
    public function setMorn($var)
    {
        GPBUtil::checkFloat($var);
        $this->Morn = $var;

        return $this;
    }

}

