<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openweathermap-store.proto

namespace Openweathermap_store;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openweathermap_store.GetWeatherDataResponse</code>
 */
class GetWeatherDataResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 LastUpdated = 1;</code>
     */
    protected $LastUpdated = 0;
    /**
     * Generated from protobuf field <code>float Lat = 2 [json_name = "lat"];</code>
     */
    protected $Lat = 0.0;
    /**
     * Generated from protobuf field <code>float Lon = 3 [json_name = "lon"];</code>
     */
    protected $Lon = 0.0;
    /**
     * Generated from protobuf field <code>string Timezone = 4 [json_name = "timezone"];</code>
     */
    protected $Timezone = '';
    /**
     * Generated from protobuf field <code>int32 TimezoneOffset = 5 [json_name = "timezone_offset"];</code>
     */
    protected $TimezoneOffset = 0;
    /**
     * Generated from protobuf field <code>.openweathermap_store.Current Current = 6 [json_name = "current"];</code>
     */
    protected $Current = null;
    /**
     * Generated from protobuf field <code>repeated .openweathermap_store.Minutely Minutely = 7 [json_name = "minutely"];</code>
     */
    private $Minutely;
    /**
     * Generated from protobuf field <code>repeated .openweathermap_store.Hourly Hourly = 8 [json_name = "hourly"];</code>
     */
    private $Hourly;
    /**
     * Generated from protobuf field <code>repeated .openweathermap_store.Daily Daily = 9 [json_name = "daily"];</code>
     */
    private $Daily;
    /**
     * Generated from protobuf field <code>repeated .openweathermap_store.Alert Alerts = 10 [json_name = "alerts"];</code>
     */
    private $Alerts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $LastUpdated
     *     @type float $Lat
     *     @type float $Lon
     *     @type string $Timezone
     *     @type int $TimezoneOffset
     *     @type \Openweathermap_store\Current $Current
     *     @type array<\Openweathermap_store\Minutely>|\Google\Protobuf\Internal\RepeatedField $Minutely
     *     @type array<\Openweathermap_store\Hourly>|\Google\Protobuf\Internal\RepeatedField $Hourly
     *     @type array<\Openweathermap_store\Daily>|\Google\Protobuf\Internal\RepeatedField $Daily
     *     @type array<\Openweathermap_store\Alert>|\Google\Protobuf\Internal\RepeatedField $Alerts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OpenweathermapStore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 LastUpdated = 1;</code>
     * @return int|string
     */
    public function getLastUpdated()
    {
        return $this->LastUpdated;
    }

    /**
     * Generated from protobuf field <code>int64 LastUpdated = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->LastUpdated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Lat = 2 [json_name = "lat"];</code>
     * @return float
     */
    public function getLat()
    {
        return $this->Lat;
    }

    /**
     * Generated from protobuf field <code>float Lat = 2 [json_name = "lat"];</code>
     * @param float $var
     * @return $this
     */
    public function setLat($var)
    {
        GPBUtil::checkFloat($var);
        $this->Lat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Lon = 3 [json_name = "lon"];</code>
     * @return float
     */
    public function getLon()
    {
        return $this->Lon;
    }

    /**
     * Generated from protobuf field <code>float Lon = 3 [json_name = "lon"];</code>
     * @param float $var
     * @return $this
     */
    public function setLon($var)
    {
        GPBUtil::checkFloat($var);
        $this->Lon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Timezone = 4 [json_name = "timezone"];</code>
     * @return string
     */
    public function getTimezone()
    {
        return $this->Timezone;
    }

    /**
     * Generated from protobuf field <code>string Timezone = 4 [json_name = "timezone"];</code>
     * @param string $var
     * @return $this
     */
    public function setTimezone($var)
    {
        GPBUtil::checkString($var, True);
        $this->Timezone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 TimezoneOffset = 5 [json_name = "timezone_offset"];</code>
     * @return int
     */
    public function getTimezoneOffset()
    {
        return $this->TimezoneOffset;
    }

    /**
     * Generated from protobuf field <code>int32 TimezoneOffset = 5 [json_name = "timezone_offset"];</code>
     * @param int $var
     * @return $this
     */
    public function setTimezoneOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->TimezoneOffset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.openweathermap_store.Current Current = 6 [json_name = "current"];</code>
     * @return \Openweathermap_store\Current|null
     */
    public function getCurrent()
    {
        return $this->Current;
    }

    public function hasCurrent()
    {
        return isset($this->Current);
    }

    public function clearCurrent()
    {
        unset($this->Current);
    }

    /**
     * Generated from protobuf field <code>.openweathermap_store.Current Current = 6 [json_name = "current"];</code>
     * @param \Openweathermap_store\Current $var
     * @return $this
     */
    public function setCurrent($var)
    {
        GPBUtil::checkMessage($var, \Openweathermap_store\Current::class);
        $this->Current = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermap_store.Minutely Minutely = 7 [json_name = "minutely"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMinutely()
    {
        return $this->Minutely;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermap_store.Minutely Minutely = 7 [json_name = "minutely"];</code>
     * @param array<\Openweathermap_store\Minutely>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMinutely($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openweathermap_store\Minutely::class);
        $this->Minutely = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermap_store.Hourly Hourly = 8 [json_name = "hourly"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHourly()
    {
        return $this->Hourly;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermap_store.Hourly Hourly = 8 [json_name = "hourly"];</code>
     * @param array<\Openweathermap_store\Hourly>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHourly($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openweathermap_store\Hourly::class);
        $this->Hourly = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermap_store.Daily Daily = 9 [json_name = "daily"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDaily()
    {
        return $this->Daily;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermap_store.Daily Daily = 9 [json_name = "daily"];</code>
     * @param array<\Openweathermap_store\Daily>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDaily($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openweathermap_store\Daily::class);
        $this->Daily = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermap_store.Alert Alerts = 10 [json_name = "alerts"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAlerts()
    {
        return $this->Alerts;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermap_store.Alert Alerts = 10 [json_name = "alerts"];</code>
     * @param array<\Openweathermap_store\Alert>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAlerts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openweathermap_store\Alert::class);
        $this->Alerts = $arr;

        return $this;
    }

}

