<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openweathermapstore.proto

namespace Openweathermapstore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openweathermapstore.Hourly</code>
 */
class Hourly extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Dt = 1 [json_name = "dt"];</code>
     */
    protected $Dt = 0;
    /**
     * Generated from protobuf field <code>float Temp = 2 [json_name = "temp"];</code>
     */
    protected $Temp = 0.0;
    /**
     * Generated from protobuf field <code>float FeelsLike = 3 [json_name = "feels_like"];</code>
     */
    protected $FeelsLike = 0.0;
    /**
     * Generated from protobuf field <code>int32 Pressure = 4 [json_name = "pressure"];</code>
     */
    protected $Pressure = 0;
    /**
     * Generated from protobuf field <code>int32 Humidity = 5 [json_name = "humidity"];</code>
     */
    protected $Humidity = 0;
    /**
     * Generated from protobuf field <code>float DewPoint = 6 [json_name = "dew_point"];</code>
     */
    protected $DewPoint = 0.0;
    /**
     * Generated from protobuf field <code>float Uvi = 7 [json_name = "uvi"];</code>
     */
    protected $Uvi = 0.0;
    /**
     * Generated from protobuf field <code>int32 Clouds = 8 [json_name = "clouds"];</code>
     */
    protected $Clouds = 0;
    /**
     * Generated from protobuf field <code>int32 Visibility = 9 [json_name = "visibility"];</code>
     */
    protected $Visibility = 0;
    /**
     * Generated from protobuf field <code>float WindSpeed = 10 [json_name = "wind_speed"];</code>
     */
    protected $WindSpeed = 0.0;
    /**
     * Generated from protobuf field <code>int32 WindDeg = 11 [json_name = "wind_deg"];</code>
     */
    protected $WindDeg = 0;
    /**
     * Generated from protobuf field <code>float WindGust = 12 [json_name = "wind_gust"];</code>
     */
    protected $WindGust = 0.0;
    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Weather Weather = 13 [json_name = "weather"];</code>
     */
    private $Weather;
    /**
     * Generated from protobuf field <code>float Pop = 14 [json_name = "pop"];</code>
     */
    protected $Pop = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Dt
     *     @type float $Temp
     *     @type float $FeelsLike
     *     @type int $Pressure
     *     @type int $Humidity
     *     @type float $DewPoint
     *     @type float $Uvi
     *     @type int $Clouds
     *     @type int $Visibility
     *     @type float $WindSpeed
     *     @type int $WindDeg
     *     @type float $WindGust
     *     @type array<\Openweathermapstore\Weather>|\Google\Protobuf\Internal\RepeatedField $Weather
     *     @type float $Pop
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Openweathermapstore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 Dt = 1 [json_name = "dt"];</code>
     * @return int
     */
    public function getDt()
    {
        return $this->Dt;
    }

    /**
     * Generated from protobuf field <code>int32 Dt = 1 [json_name = "dt"];</code>
     * @param int $var
     * @return $this
     */
    public function setDt($var)
    {
        GPBUtil::checkInt32($var);
        $this->Dt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Temp = 2 [json_name = "temp"];</code>
     * @return float
     */
    public function getTemp()
    {
        return $this->Temp;
    }

    /**
     * Generated from protobuf field <code>float Temp = 2 [json_name = "temp"];</code>
     * @param float $var
     * @return $this
     */
    public function setTemp($var)
    {
        GPBUtil::checkFloat($var);
        $this->Temp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float FeelsLike = 3 [json_name = "feels_like"];</code>
     * @return float
     */
    public function getFeelsLike()
    {
        return $this->FeelsLike;
    }

    /**
     * Generated from protobuf field <code>float FeelsLike = 3 [json_name = "feels_like"];</code>
     * @param float $var
     * @return $this
     */
    public function setFeelsLike($var)
    {
        GPBUtil::checkFloat($var);
        $this->FeelsLike = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Pressure = 4 [json_name = "pressure"];</code>
     * @return int
     */
    public function getPressure()
    {
        return $this->Pressure;
    }

    /**
     * Generated from protobuf field <code>int32 Pressure = 4 [json_name = "pressure"];</code>
     * @param int $var
     * @return $this
     */
    public function setPressure($var)
    {
        GPBUtil::checkInt32($var);
        $this->Pressure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Humidity = 5 [json_name = "humidity"];</code>
     * @return int
     */
    public function getHumidity()
    {
        return $this->Humidity;
    }

    /**
     * Generated from protobuf field <code>int32 Humidity = 5 [json_name = "humidity"];</code>
     * @param int $var
     * @return $this
     */
    public function setHumidity($var)
    {
        GPBUtil::checkInt32($var);
        $this->Humidity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float DewPoint = 6 [json_name = "dew_point"];</code>
     * @return float
     */
    public function getDewPoint()
    {
        return $this->DewPoint;
    }

    /**
     * Generated from protobuf field <code>float DewPoint = 6 [json_name = "dew_point"];</code>
     * @param float $var
     * @return $this
     */
    public function setDewPoint($var)
    {
        GPBUtil::checkFloat($var);
        $this->DewPoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Uvi = 7 [json_name = "uvi"];</code>
     * @return float
     */
    public function getUvi()
    {
        return $this->Uvi;
    }

    /**
     * Generated from protobuf field <code>float Uvi = 7 [json_name = "uvi"];</code>
     * @param float $var
     * @return $this
     */
    public function setUvi($var)
    {
        GPBUtil::checkFloat($var);
        $this->Uvi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Clouds = 8 [json_name = "clouds"];</code>
     * @return int
     */
    public function getClouds()
    {
        return $this->Clouds;
    }

    /**
     * Generated from protobuf field <code>int32 Clouds = 8 [json_name = "clouds"];</code>
     * @param int $var
     * @return $this
     */
    public function setClouds($var)
    {
        GPBUtil::checkInt32($var);
        $this->Clouds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Visibility = 9 [json_name = "visibility"];</code>
     * @return int
     */
    public function getVisibility()
    {
        return $this->Visibility;
    }

    /**
     * Generated from protobuf field <code>int32 Visibility = 9 [json_name = "visibility"];</code>
     * @param int $var
     * @return $this
     */
    public function setVisibility($var)
    {
        GPBUtil::checkInt32($var);
        $this->Visibility = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float WindSpeed = 10 [json_name = "wind_speed"];</code>
     * @return float
     */
    public function getWindSpeed()
    {
        return $this->WindSpeed;
    }

    /**
     * Generated from protobuf field <code>float WindSpeed = 10 [json_name = "wind_speed"];</code>
     * @param float $var
     * @return $this
     */
    public function setWindSpeed($var)
    {
        GPBUtil::checkFloat($var);
        $this->WindSpeed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 WindDeg = 11 [json_name = "wind_deg"];</code>
     * @return int
     */
    public function getWindDeg()
    {
        return $this->WindDeg;
    }

    /**
     * Generated from protobuf field <code>int32 WindDeg = 11 [json_name = "wind_deg"];</code>
     * @param int $var
     * @return $this
     */
    public function setWindDeg($var)
    {
        GPBUtil::checkInt32($var);
        $this->WindDeg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float WindGust = 12 [json_name = "wind_gust"];</code>
     * @return float
     */
    public function getWindGust()
    {
        return $this->WindGust;
    }

    /**
     * Generated from protobuf field <code>float WindGust = 12 [json_name = "wind_gust"];</code>
     * @param float $var
     * @return $this
     */
    public function setWindGust($var)
    {
        GPBUtil::checkFloat($var);
        $this->WindGust = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Weather Weather = 13 [json_name = "weather"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWeather()
    {
        return $this->Weather;
    }

    /**
     * Generated from protobuf field <code>repeated .openweathermapstore.Weather Weather = 13 [json_name = "weather"];</code>
     * @param array<\Openweathermapstore\Weather>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWeather($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Openweathermapstore\Weather::class);
        $this->Weather = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Pop = 14 [json_name = "pop"];</code>
     * @return float
     */
    public function getPop()
    {
        return $this->Pop;
    }

    /**
     * Generated from protobuf field <code>float Pop = 14 [json_name = "pop"];</code>
     * @param float $var
     * @return $this
     */
    public function setPop($var)
    {
        GPBUtil::checkFloat($var);
        $this->Pop = $var;

        return $this;
    }

}

