<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openweathermap-store.proto

namespace Openweathermap_store;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openweathermap_store.Minutely</code>
 */
class Minutely extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Dt = 1 [json_name = "dt"];</code>
     */
    protected $Dt = 0;
    /**
     * Generated from protobuf field <code>float Precipitation = 2 [json_name = "precipitation"];</code>
     */
    protected $Precipitation = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Dt
     *     @type float $Precipitation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OpenweathermapStore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 Dt = 1 [json_name = "dt"];</code>
     * @return int
     */
    public function getDt()
    {
        return $this->Dt;
    }

    /**
     * Generated from protobuf field <code>int32 Dt = 1 [json_name = "dt"];</code>
     * @param int $var
     * @return $this
     */
    public function setDt($var)
    {
        GPBUtil::checkInt32($var);
        $this->Dt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Precipitation = 2 [json_name = "precipitation"];</code>
     * @return float
     */
    public function getPrecipitation()
    {
        return $this->Precipitation;
    }

    /**
     * Generated from protobuf field <code>float Precipitation = 2 [json_name = "precipitation"];</code>
     * @param float $var
     * @return $this
     */
    public function setPrecipitation($var)
    {
        GPBUtil::checkFloat($var);
        $this->Precipitation = $var;

        return $this;
    }

}

